### ISSUE TITLE
Help Needed?

### ISSUE THREAD

**Issue by Tokazama** [JuliaNeuroscience/GIFTI.jl#2]
Thanks for getting this package going. I plan on using GIFTI files more in the near future and wanted to see if you'd like/need help with this package. Just for reference, I've started https://github.com/JuliaNeuroscience and I'm trying to get more neuroscience related filetypes supported.

I will likely include CIFTI support in a package in the future too. Considering how much these file types have in common I thought it might make sense to getting some common stuff in place early on.

**Comment by rdeits** [comment]
Thanks for the contact! I don't actually *do* any neuroscience--I wrote this package because I got my hands on some GIFTI meshes of my own brain and wanted to be able to render them in https://github.com/rdeits/MeshCat.jl . I haven't done much with it since then, except to upgrade it to Julia 1.0 support. I'd be happy to transfer the repo to the JuliaNeuroscience org if it would have a good home there.

**Comment by Tokazama** [comment]
I sent you an invitation to the organization. There's absolutely no pressure to transfer it over if you decide you want to maintain it independently but it would be a great resource to have if we'd like to get Julia native connectomics established.

**Comment by rdeits** [comment]
Hi @Tokazama I'm sorry for dropping the ball on this. Can you re-invite me and I'll transfer the repo right away?

**Comment by rdeits** [comment]
done!
